In [2]:
import numpy as np

hello


In [3]:
alpha = 1/2
a = np.array([2,3])
alpha * a

array([1. , 1.5])

In [4]:
#교환
alpha * a == a * alpha

array([ True,  True])

In [5]:
#분배
beta = 0.7
(alpha + beta) * a == alpha * a + beta * a

array([ True,  True])

In [11]:
#01
#1) 1부터 10까지의 수로 구성된 벡터 생성
x = np.arange(1, 11, 1)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
# 7번째 값만 1이고 나머지는 0인 e7 벡터 생성
x = np.zeros(7)
x[6] = 1
print(x)

[0. 0. 0. 0. 0. 0. 1.]


In [20]:
# [1,3], [3,1] 벡터의 선형 결합으로 [2.5, 3.5] 벡터 생성했을때 B1, B2값
A = np.array([[1,3],[3,1]])
B = np.array([2.5, 3.5])
C = np.linalg.solve(A, B)
print(C)

[1.  0.5]
