In [11]:
import numpy as np

In [3]:
A = np.array([[-1.086, 0.997, 0.283, -1.506], 
              [-0.579, 1.651, -2.427, -0.429], 
              [ 1.266, -0.867, -0.679, -0.095], 
              [ 1.491, -0.639, -0.444, -0.434]]) 
A

array([[-1.086,  0.997,  0.283, -1.506],
       [-0.579,  1.651, -2.427, -0.429],
       [ 1.266, -0.867, -0.679, -0.095],
       [ 1.491, -0.639, -0.444, -0.434]])

In [5]:
B = np.array([['a', 'c'], 
              ['b', 'd']], dtype='object') 
B

array([['a', 'c'],
       ['b', 'd']], dtype=object)

In [6]:
A = np.array([[ 3, 3, 7, 2], 
              [ 4, 11, 10, 7], 
              [ 2, 1, 2, 10]]) 
A.shape

(3, 4)

In [9]:
A.size

12

In [11]:
# 행 벡터
A[0,:]

array([3, 3, 7, 2])

In [12]:
# 열 벡터
A[:,0]

array([3, 4, 2])

In [13]:
A[0, 0]

3

In [14]:
A[1,3]

7

In [13]:
# 과제 6.1 
# 1번째와 2번째 열벡터의 내적을 구해보자.
A = np.array([[ 3, 3, 7, 2], 
              [ 4, 11, 10, 7], 
              [ 2, 1, 2, 10]]) 

A_col1 = A[:,0]
A_col2 = A[:,1]
np.dot(A_col1, A_col2)

55

In [17]:
# 과제 6.2
# 모든 행 벡터의 노름을 구해보자.
A_row1 = A[0,:]
A_row2 = A[1,:]
A_row3 = A[2,:]
print(la.norm(A_row1))
print(la.norm(A_row2))
print(la.norm(A_row3))


8.426149773176359
16.911534525287763
10.44030650891055


In [19]:
# 과제 6.3
# 𝑎22 ,𝑎24의 값을 찾기 위한 파이썬 프로그램을 구성해보자.
print(A[1,1], A[1,3])

11 7


In [15]:
# 행렬 전치의 성질
A = np.arange(1, 7).reshape(2, 3) 
B = np.arange(3, 9).reshape(2, 3)
A.T + B.T == (A + B).T

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [17]:
print(A)
print(B)

[[1 2 3]
 [4 5 6]]
[[3 4 5]
 [6 7 8]]


In [16]:
c = 0.1
(c*A).T == c*A.T

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [20]:
# 과제 7.1
# A + 0.1B를 구해보자

A = np.array([[ 1, 2, 3], 
              [ 4, 5, 6]]) 

B = np.array([[ 3, 4, 5 ], 
              [ 6, 7, 8 ]])

print(A + 0.1*B)


[[1.3 2.4 3.5]
 [4.6 5.7 6.8]]


In [21]:
# 과제 7.2
# (0.1B)T = 0.1BT 임을 알아보자.

print((0.1*B).T == 0.1*B.T)

[[ True  True]
 [ True  True]
 [ True  True]]


- 행렬 곱

In [6]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])

In [7]:
A @ B

array([[22, 28],
       [49, 64]])

In [8]:
np.matmul(A, B)

array([[22, 28],
       [49, 64]])

In [9]:
A.dot(B)

array([[22, 28],
       [49, 64]])

In [11]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [12]:
A @ B

array([[19, 22],
       [43, 50]])

In [13]:
B @ A

array([[23, 34],
       [31, 46]])

In [14]:
(A @ B).T

array([[19, 43],
       [22, 50]])

In [15]:
B.T @ A.T

array([[19, 43],
       [22, 50]])

In [30]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[3,4,5],[6,7,8]])

In [31]:
# 과제 8.1
A.T @ B

array([[27, 32, 37],
       [36, 43, 50],
       [45, 54, 63]])

In [32]:
# 과제 8.2
result1 = (A.T @ B).T
result2 = B.T @ A
result1 == result2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

- 부분 행렬

In [34]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [35]:
A[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [37]:
A[:, 1:3]

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

In [38]:
A[[0,2], :][:, [1,2]]

array([[2, 3],
       [8, 9]])

In [22]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [23]:
# 과제 9.1
print(A[1,1])
print(A[2,2])

5
9


In [29]:
#과제 9.2
print(A[2:4, 1:4])

[[ 8  9]
 [11 12]]


- 특별한 행렬

In [46]:
#영 행렬
size = 3
np.zeros(shape=(size, size))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
#항등 행렬
np.identity(n=size)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
#항등 행렬
size = 3
np.eye(N=size)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
#대각 행렬
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [55]:
np.diag([[2,3,2],[1,2,7],[8,9,10]]) #대각선 값만 받아옴

array([ 2,  2, 10])

In [56]:
#삼각 행렬
np.triu([[1,2,3],
         [1,2,7],
         [7,8,5]], k=0) #upper triangle

array([[1, 2, 3],
       [0, 2, 7],
       [0, 0, 5]])

In [61]:
np.tril([[1,2,3],
         [1,2,7],
         [7,8,5]], k=0) #lower triangle

array([[1, 0, 0],
       [1, 2, 0],
       [7, 8, 5]])

In [62]:
A = np.array([[1,0],[0,-1]])

In [63]:
A.T @ A

array([[1, 0],
       [0, 1]])

In [64]:
A @ A.T

array([[1, 0],
       [0, 1]])

In [75]:
# 과제 10.1 대각 원소로 구성된 대각행렬 구하기
A = np.array(([7,2,0],[2,1,3],[4,8,3]))
A = np.diag(A)
np.diag(A)

array([[7, 0, 0],
       [0, 1, 0],
       [0, 0, 3]])

In [31]:
# 과제 10.2 아무 A행렬로 B행렬이 대칭행렬인지 확인하기
A = np.array(([7,2,0],
              [2,1,3],
              [4,8,3]))
B = A.T @ A
print(B)
print(B.T)

[[69 48 18]
 [48 69 27]
 [18 27 18]]
[[69 48 18]
 [48 69 27]
 [18 27 18]]


In [85]:
#10.3 A행렬이 직교행렬인지 확인하기
A = np.array(([1,0,0],
              [0,-1,0],
              [0,0,-1]))
print(A @ A.T) # A @ A.T = I
print(A.T @ A) # A.T @ A = I
print(A @ A.T == A @ A.T)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


- 선형방정식과 QR분해 (Q:직교행렬, R:상삼각행렬)

In [88]:
A = np.array(([1,1],[1/2, -1]))
A

array([[ 1. ,  1. ],
       [ 0.5, -1. ]])

In [93]:
Q,R = np.linalg.qr(A)

In [7]:
from scipy import linalg as la
Q, R = la.qr(A)

In [90]:
np.round(Q,3)

array([[-0.89442719, -0.4472136 ],
       [-0.4472136 ,  0.89442719]])

In [96]:
np.round(R,3)

array([[-1.118, -0.447],
       [ 0.   , -1.342]])

In [98]:
XTX = A.T@A
XTX

array([[1.25, 0.5 ],
       [0.5 , 2.  ]])

In [99]:
Q,R = la.qr(XTX)
R.round(2)

array([[-1.35, -1.21],
       [ 0.  ,  1.67]])

In [100]:
b = np.array([4,2])
np.round(Q.T @ b, 2)

array([-4.46,  0.37])

In [48]:
# 과제 11.1
# u 벡터 구하기
A = np.array(([5,1,5],
              [3,9,8],
              [2,1,4]))

#첫 번째 열벡터 추출
a = A[:,0].reshape(-1, 1)
print(a)

# 하우스홀더 행렬 Q1 생성
size = A.shape[0]
e1 = np.identity(n=size)[:,0].reshape(-1,1)

#u 벡터 구성
u = a - la.norm(a)*e1
u

[[5]
 [3]
 [2]]


array([[-1.164414],
       [ 3.      ],
       [ 2.      ]])

In [51]:
# 과제 11.2
# v 벡터 구하기
v = u / la.norm(u)
v

array([[-0.30732141],
       [ 0.79178387],
       [ 0.52785591]])

In [53]:
# 과제 11.3  
# Q1 = I3 - 2vv.T
Q1 = np.identity(n=size) -2 *v@v.T
np.round(Q1,2)

array([[ 0.81,  0.49,  0.32],
       [ 0.49, -0.25, -0.84],
       [ 0.32, -0.84,  0.44]])

In [54]:
# 과제 11.4
# Q1A 값 구하기 -> 하우스-홀더 변환과 변환 후의 결과
np.round(Q1 @ A, 2)

array([[ 6.16,  5.52,  9.25],
       [-0.  , -2.63, -2.94],
       [-0.  , -6.76, -3.29]])

- 역행렬

In [9]:
# 행렬의 계수
A = np.random.RandomState(123).randint(1, 9, 9).reshape(3, 3) 
A

array([[7, 6, 7],
       [3, 5, 3],
       [7, 2, 4]])

In [3]:
# 행렬 계수 구하기
np.linalg.matrix_rank(A)

#A = np.array(([7,2,0],[2,1,3],[7,2,0]))
#np.linalg.matrix_rank(A)

3

In [10]:
# 역행렬 구하기
A_inverse = la.inv(A) 
np.round(A_inverse, 2)

array([[-0.27,  0.2 ,  0.33],
       [-0.18,  0.41,  0.  ],
       [ 0.57, -0.55, -0.33]])

In [4]:
#과제 12.1

2