In [6]:
import numpy as np
from scipy import linalg as la

# 과제 1

In [10]:
#과제 1
#구성된 벡터는 서로 독립인지를 확인 해보자.
a1 = np.array([1,2,3])
a2 = np.array([1,1,2])
a3 = np.array([0.5, 2, 1.5])

A = np.array([[1,2,3],[1,1,2], [0.5, 2, 1.5]])
B = np.array([0,0,0])
C = np.linalg.solve(A, B)
print(C)

[ 0. -0. -0.]


# 과제2

In [11]:
#과제 2
#2차원 즉, 평면에서의 기저를 찾아보자.
print("(2,0), (0,2)")
print("(x,0), (0,y) 꼴로 된 벡터는 기저가 될 수 있으며, 평면상 모든 점을 생성할 수 있다.")

(2,0), (0,2)
(x,0), (0,y) 꼴로 된 벡터는 기저가 될 수 있으며, 평면상 모든 점을 생성할 수 있다.


# 과제3

In [12]:
#과제 3
# a1, a2, a3가 서로 직교 정교 벡터임을 확인해보자.

#직교정규 벡터 확인
a1 = np.array([0,0,1]).reshape(-1, 1)
a2 = 1/np.sqrt(2) * np.array([1,1,0]).reshape(-1, 1)
a3 = 1/np.sqrt(2) * np.array([1,-1,0]).reshape(-1, 1)

#열의 곱 0
print('각 벡터의 직교 여부')
print("a1.T @ a2 =",np.dot(a1.T,a2))
print("a1.T @ a3 =",np.dot(a1.T,a3))
print("a2.T @ a1 =",np.dot(a2.T,a1))
print("a2.T @ a3 =",np.dot(a2.T,a3))
print("a3.T @ a1 =",np.dot(a3.T,a1))
print("a3.T @ a2 =",np.dot(a3.T,a2))

print()
#노름 1
print('각 벡터의 노름이 1')
print("a1 norm :",la.norm(a1))
print("a2 norm :",la.norm(a2))
print("a3 norm :",la.norm(a3))

A = np.concatenate((a1,a2,a3), axis=1)
print(np.round(A.T @ A, 3))

각 벡터의 직교 여부
a1.T @ a2 = [[0.]]
a1.T @ a3 = [[0.]]
a2.T @ a1 = [[0.]]
a2.T @ a3 = [[0.]]
a3.T @ a1 = [[0.]]
a3.T @ a2 = [[0.]]

각 벡터의 노름이 1
a1 norm : 1.0
a2 norm : 0.9999999999999999
a3 norm : 0.9999999999999999
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]
