In [1]:
import numpy as np
from scipy import linalg as la

### 1) A의 행렬식인 |A|를 구해보자

In [3]:
A = np.array(([2,2,6],
              [1,3,9],
              [6,1,0]))
np.round(la.det(A))

-12.0

### 2) A의 첫번째 행과 두번째 행을 바꾸는 행렬 𝐸1 를 구한 후 |𝐸1A| 를 구해보자.

In [25]:
#첫번째 행과 두번째 행 교환 - 치환행렬
E1 = np.array(([0,1,0],
               [1,0,0],
               [0,0,1]))
print("**행렬 A")
print(A)
print("**A의 첫번째 행과 두번째 행을 바꾸는 행렬 E1")
print(E1)
print("**E1@A")
print(E1@A)
print("============")
print("**|E1A| 결과 값")
print(la.det(E1@A))
print("-> detA = -detA`")

**행렬 A
[[2 2 6]
 [1 3 9]
 [6 1 0]]
**A의 첫번째 행과 두번째 행을 바꾸는 행렬 E1
[[0 1 0]
 [1 0 0]
 [0 0 1]]
**E1@A
[[1 3 9]
 [2 2 6]
 [6 1 0]]
**|E1A| 결과 값
11.999999999999996
-> detA = -detA`


### 3) A의 첫번째 행을 1/2배 하는 행렬 𝐸2 을 구한 후 |𝐸2A| 구해보자.

In [24]:
E2 = np.array(([0.5,0,0],
               [0,1,0],
               [0,0,1]))
print("**행렬 A")
print(A)
print("**A의 첫번째 행을 1/2배 하는 행렬 𝐸2")
print(E2)
print("**E2@A")
print(E2@A)
print("============")
print("**|E2A| 결과 값")
print(la.det(E2@A))

**행렬 A
[[2 2 6]
 [1 3 9]
 [6 1 0]]
**A의 첫번째 행을 1/2배 하는 행렬 𝐸2
[[0.5 0.  0. ]
 [0.  1.  0. ]
 [0.  0.  1. ]]
**E2@A
[[1. 1. 3.]
 [1. 3. 9.]
 [6. 1. 0.]]
**|E2A| 결과 값
-6.000000000000002


### 4) A의 첫번째 행을 1/2배 한 후 두번째 행에 그 값을 더하는 행렬 𝐸3 를 구한 후 |𝐸3A| 을구해보자

In [28]:
E3 = np.array(([1,0,0],
               [0.5,1,0],
               [0,0,1]))

print("**행렬 A")
print(A)
print("**A의 첫번째 행을 1/2배 한 행렬")
print(E2@A)
print("**A의 첫번째 행을 1/2배 한 후 두번째 행에 그 값을 더하는 행렬 𝐸3")
print(E3)
print("**E3@A")
print(E3@A)
print("============")
print("**|E3A| 결과 값")
print(la.det(E3@A))
print("-> detA = detA`")

**행렬 A
[[2 2 6]
 [1 3 9]
 [6 1 0]]
**A의 첫번째 행을 1/2배 한 행렬
[[1. 1. 3.]
 [1. 3. 9.]
 [6. 1. 0.]]
**A의 첫번째 행을 1/2배 한 후 두번째 행에 그 값을 더하는 행렬 𝐸3
[[1.  0.  0. ]
 [0.5 1.  0. ]
 [0.  0.  1. ]]
**E3@A
[[ 2.  2.  6.]
 [ 2.  4. 12.]
 [ 6.  1.  0.]]
**|E3A| 결과 값
-12.000000000000005
-> detA = detA`


### 5) 고유값을 구해보자.

In [29]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [32]:
w, v = la.eig(I)
print("고유값")
print(w)

고유값
[1.+0.j 1.+0.j]


### 6) 서로 직교하면서 각각의 노름이 1인 고유벡터 2개를 구해보자

In [44]:
print("고유 벡터 2개")
print("V1 ->",v[0])
print("V2 ->",v[1])

print("V1 norm ->", la.norm(v[0]))
print("V2 norm ->", la.norm(v[1]))
print("직교 여부")
print("V1.T @ V2 ->",v[0].T @ v[1])
print("V1 @ V2.T ->",v[0] @ v[1].T)
print("V2.T @ V1 ->",v[1].T @ v[0])
print("V2.T @ V1 ->",v[1].T @ v[0])

고유 벡터 2개
V1 -> [1. 0.]
V2 -> [0. 1.]
V1 norm -> 1.0
V2 norm -> 1.0
직교 여부
V1.T @ V2 -> 0.0
V1 @ V2.T -> 0.0
V2.T @ V1 -> 0.0
V2.T @ V1 -> 0.0
