In [2]:
import numpy as np

In [3]:
A = np.array([[-1.086, 0.997, 0.283, -1.506], 
              [-0.579, 1.651, -2.427, -0.429], 
              [ 1.266, -0.867, -0.679, -0.095], 
              [ 1.491, -0.639, -0.444, -0.434]]) 
A

array([[-1.086,  0.997,  0.283, -1.506],
       [-0.579,  1.651, -2.427, -0.429],
       [ 1.266, -0.867, -0.679, -0.095],
       [ 1.491, -0.639, -0.444, -0.434]])

In [5]:
B = np.array([['a', 'c'], 
              ['b', 'd']], dtype='object') 
B

array([['a', 'c'],
       ['b', 'd']], dtype=object)

In [6]:
A = np.array([[ 3, 3, 7, 2], 
              [ 4, 11, 10, 7], 
              [ 2, 1, 2, 10]]) 
A.shape

(3, 4)

In [9]:
A.size

12

In [11]:
# 행 벡터
A[0,:]

array([3, 3, 7, 2])

In [12]:
# 열 벡터
A[:,0]

array([3, 4, 2])

In [13]:
A[0, 0]

3

In [14]:
A[1,3]

7

과제 06
1) 행렬 A = [3 3 7 2 
           4 11 10 7
           2 1 2 10]
에서 1번째와 2번째 열벡터의 내적을 구해보자. 

(.dot inner product)


2) 행렬 A =
3 3 7 2
4 11 10 7
2 1 2 10
에서 모든 행벡터의 노름을 구해보자. 

a1, a2, a3 norm


3) 행렬 A =
3 3 7 2
4 11 10 7
2 1 2 10
에서 [𝑎22 ,𝑎24] 의 값을 찾기 위한 파이썬 프로그 램을 구성해보자.

A[A[1,1], A[1,3]]

In [15]:
# 행렬 전치의 성질
A = np.arange(1, 7).reshape(2, 3) 
B = np.arange(3, 9).reshape(2, 3)
A.T + B.T == (A + B).T

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [17]:
print(A)
print(B)

[[1 2 3]
 [4 5 6]]
[[3 4 5]
 [6 7 8]]


In [16]:
c = 0.1
(c*A).T == c*A.T

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

1) 행렬 A =
1 2 3
4 5 6
, B =
3 4 5
6 7 8
에 대하여 A + 0.1B를 구해보 자.

2) 행렬 B =
3 4 5
6 7 8
에 대하여 0.1B T = 0.1B T 임을 알아보자.