In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stats

%precision 3

'%.3f'

모집단 평균의 추정 with known sigma

In [3]:
amuse_df = pd.read_excel('./data/Amuse.xlsx')
amuse = np.array(amuse_df['Amount Spent'])
amuse

array([ 72,  91,  74, 115,  71, 120,  37,  96,  91, 105, 104,  89,  70,
       125,  43,  61, 102,  85,  26,  88,  80,  76,  70,  46,  79,  71,
        78,  55, 104,  62,  84,  78,  54,  47, 109, 105,  65, 122, 112,
        59, 100,  85,  82,  60,  65,  98,  61,  42, 114,  93, 110,  95,
        62, 119,  68,  98,  89, 118,  63,  87,  72,  92,  89,  72,  46,
       108,  63,  91,  86,  93,  84, 124,  75,  82,  56,  58,  64,  72,
        97,  66,  80,  85,  75,  99, 112,  93,  76,  76,  89,  99, 113,
        68,  80,  52,  90,  86,  95,  57,  71,  84])

In [8]:
rv = stats.norm(0,1)
std = 20
n = len(amuse)
xbar = np.mean(amuse)

se = std / np.sqrt(n)
e = rv.isf(0.025) * std / np.sqrt(n)
lcl = xbar - e
ucl = xbar + e

rv.isf(0.025), se, e, lcl, ucl

(1.960, 2.000, 3.920, 78.080, 85.920)

모집단 평균의 추정 with unknown sigma

In [10]:
sales_df = pd.read_excel('./data/SalesDays.xlsx')
sales_days = np.array(sales_df['Days'])

sales_days

array([52, 44, 55, 44, 45, 59, 50, 54, 62, 46, 54, 42, 60, 62, 43, 42, 48,
       55, 57, 56])

In [13]:
n = len(sales_days)
rv_t = stats.t(df = n-1)
xbar = np.mean(sales_days)
sample_std = np.std(sales_days, ddof=1)
se = sample_std / np.sqrt(n)

xbar, sample_std, se

(51.500, 6.840, 1.530)

In [14]:
e = rv_t.isf(0.025) * se
e

3.201

In [15]:
lcl = xbar - e
ucl = xbar + e

lcl, ucl

(48.299, 54.701)

표본 규모 결정

In [20]:
e = 2
z = rv.isf(0.025)
sample_std = 9.65

n = (z**2) * (sample_std**2) / e**2
N = (np.ceil(n))

n, N

(89.432, 90.000)

모집단 비율 추정
(남성 고객 비율의 95% 신뢰구간)

In [23]:
hairshop_df = pd.read_excel('./data/Hairshop.xlsx')
guest = np.array(hairshop_df['Guest'])
guest.astype('str')

array(['Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Male',
       'Female', 'Female', 'Female', 'Female', 'Female', 'Female',
       'Female', 'Female', 'Female', 'Female', 'Male', 'Female', 'Female',
       'Female', 'Female', 'Female', 'Female', 'Male', 'Female', 'Female',
       'Female', 'Female', 'Female', 'Male', 'Female', 'Female', 'Female',
       'Male', 'Female', 'Male', 'Female', 'Female', 'Female', 'Female',
       'Female', 'Female', 'Female', 'Female', 'Female', 'Male', 'Male',
       'Female', 'Female', 'Female', 'Female', 'Female', 'Male', 'Female',
       'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female',
       'Male', 'Female', 'Female', 'Male', 'Female', 'Female', 'Female',
       'Female', 'Male', 'Female', 'Male', 'Female', 'Female', 'Female',
       'Female', 'Female', 'Female', 'Female', 'Male', 'Male', 'Female',
       'Female', 'Female', 'Male', 'Male', 'Female', 'Female', 'Female',
       'Female', 'Female', 'Female', 'Female', 'Female'

In [25]:
n = len(guest)

male = 0
female = 0

for i in np.arange(n):
    if guest[i] == 'Male':
        male += 1
    else:
        female += 1

n, male, female

(400, 92, 308)

In [26]:
p_bar = male / n

p_bar

0.230

In [27]:
e = rv.isf(0.025) * np.sqrt(p_bar * (1 - p_bar) / n)
e

0.041

In [28]:
lcl = p_bar - e
ucl = p_bar + e

lcl, ucl

(0.189, 0.271)

In [29]:
e = 0.025

n = rv.isf(0.025) ** 2 * p_bar * (1 - p_bar) / e ** 2
N = np.ceil(n)

n, N

(1088.516, 1089.000)

모집단 비율의 구간 추정

In [31]:
syrup_df = pd.read_excel('./data/Syrup.xlsx')
syrup = np.array(syrup_df['Fills'])

syrup

array([ 999.6, 1000.5, 1001.3,  999.5, 1000.4, 1000.7,  999.7, 1000.7,
       1000.1, 1000.1,  999.3,  999.6,  999.4,  998.3, 1000.1, 1000.1,
        999.1, 1000. ,  999.2,  999.6,  999.5,  997.8,  998.3,  999.2,
        999.9])

In [33]:
n = len(syrup)

rv_chi2 = stats.chi2(df = n-1)

sample_std = np.std(syrup, ddof=1)
sample_var = sample_std ** 2

n, sample_std, sample_var

(25, 0.796, 0.633)

In [34]:
lcl = (n-1) * sample_var / rv_chi2.isf(0.025)
ucl = (n-1) * sample_var / rv_chi2.isf(1-0.025)

lcl, ucl

(0.386, 1.226)