In [2]:
import numpy as np
import pandas as pd
import scipy.stats as stats

%precision 3

'%.3f'

모집단 평균에 대한 가설 검정 : 모집단 분산을 아는 경우

윤활유 용량 사례1 : 왼쪽 꼬리 검정

In [4]:
lubricant_df = pd.read_excel('./data/lubricant.xlsx')

lubricant_df.head()

Volume
0    2.89
1    2.86
2    2.94
3    2.77
4    2.74

In [5]:
volume = np.array(lubricant_df['Volume'])

volume, len(volume)

(array([2.89, 2.86, 2.94, 2.77, 2.74, 2.82, 2.94, 3.15, 2.91, 2.94, 2.84,
        2.9 , 2.86, 2.77, 3.1 , 2.6 , 2.82, 3.21, 3.02, 3.05, 2.54, 3.05,
        2.65, 2.76, 3.18, 2.66, 3.11, 3.13, 3.14, 2.95, 2.96, 2.93, 3.18,
        2.93, 2.86, 2.96]),
 36)

In [7]:
n = len(volume)
mu_0 = 3
x_bar = np.mean(volume)
std = 0.18
se = std / np.sqrt(n)
alpha = 0.05

임계값 접근법 Critical Value(검정 통계량) : CV

In [14]:
def z_test_cv(n, mu_0, x_bar, std, alpha):
    rv_z = stats.norm(0, 1)
    se = std / np.sqrt(n)
    z = (x_bar - mu_0) / se

    cv = rv_z.isf(alpha)

    if(abs(z) >= cv):
        print(f"z = {z: .2f}, |z| = {abs(z): .2f} >= cv = {cv: .2f}입니다. \n 따라서 귀무가설을 기각합니다.")
    else:
        print(f"z = {z: .2f}, |z| = {abs(z): .2f} < cv = {cv: .2f}입니다. \n 따라서 귀무가설을 기각하지 않습니다.")

In [15]:
z_test_cv(n, mu_0, x_bar, std, alpha)

z = -2.67, |z| =  2.67 >= cv =  1.64입니다. 
 따라서 귀무가설을 기각합니다.


p-값 접근법 : p-value

In [16]:
def z_test_p(n, mu_0, x_bar, std, alpha):
    rv_z = stats.norm(0, 1)
    se = std / np.sqrt(n)
    z = (x_bar - mu_0) / se

    if(z < 0):
        p_value = rv_z.cdf(z)
    else:
        p_value = rv_z.sf(z)

    if p_value < alpha:
        print(f"p_value = {p_value: .4f} < alpha = {alpha : .2f}입니다. \n 따라서 귀무가설을 기각합니다.")
    else:
        print(f"p_value = {p_value: .4f} < alpha >= {alpha : .2f}입니다. \n 따라서 귀무가설을 기각하지 않습니다.")

z_test_p(n, mu_0, x_bar, std, alpha)

p_value =  0.0038 < alpha =  0.05입니다. 
 따라서 귀무가설을 기각합니다.


윤활유 용량 사례2 : 양쪽 꼬리 검정

임계값 접근법

In [18]:
def z_test2_cv(n, mu_0, x_bar, std, alpha):
    rv_z = stats.norm(0, 1) #평균0, 분산1
    se = std / np.sqrt(n)
    z = (x_bar - mu_0) / se

    if(z < 0):
        cv = rv_z.ppf(alpha / 2)
    else:
        cv = rv_z.isf(alpha / 2)

    cv1 = -np.abs(cv)
    cv2 = np.abs(cv)
    
    if(z <= cv1):
        print(f"z = {z: .2f} <= cv1 = {cv: .2f}입니다. \n 따라서 귀무가설을 기각합니다.")
    elif(z >= cv2):
        print(f"z = {z: .2f} >= cv2 = {cv: .2f}입니다. \n 따라서 귀무가설을 기각합니다.")
    else:
        print(f"cv1 = {z: .2f} < z = {cv: .2f} < cv2 입니다. \n 따라서 귀무가설을 기각합니다.")
    # if(-np.abs(cv) >= cv):
    #     print(f"z = {z: .2f}, |z| = {abs(z): .2f} >= cv = {cv: .2f}입니다. \n 따라서 귀무가설을 기각합니다.")
    # else:
    #     print(f"z = {z: .2f}, |z| = {abs(z): .2f} < cv = {cv: .2f}입니다. \n 따라서 귀무가설을 기각하지 않습니다.")

z_test2_cv(n, mu_0, x_bar, std, alpha)

z = -2.67 <= cv1 = -1.96입니다. 
 따라서 귀무가설을 기각합니다.


p-값 접근법

In [20]:
def z_test2_p(n, mu_0, x_bar, std, alpha):
    rv_z = stats.norm(0, 1) #평균0, 분산1
    se = std / np.sqrt(n)
    z = (x_bar - mu_0) / se

    if(z < 0):
        p_value = rv_z.cdf(z) * 2
    else:
        p_value = rv_z.sf(z) * 2
    
    if(p_value < alpha):
        print(f"p_value = {p_value: .4f} < alpha = {alpha: .2f}입니다. 따라서 귀무가설을 기각합니다.")
    else:
        print(f"p_value = {p_value: .4f} >= alpha = {alpha: .2f}입니다. 따라서 귀무가설을 기각하지 않습니다.")


z_test2_p(n, mu_0, x_bar, std, alpha)

p_value =  0.0077 < alpha =  0.05입니다. 따라서 귀무가설을 기각합니다.


In [23]:
chatbot_df = pd.read_excel('./data/Chatbot.xlsx')

chatbot_df.head()

Rating
0       8
1       6
2       7
3       7
4       5

In [24]:
rating = np.array(chatbot_df['Rating'])

rating, len(rating)

(array([ 8,  6,  7,  7,  5,  9,  8, 10,  8,  5,  7,  7,  9,  8,  6,  6,  7,
         8,  8,  7,  8,  7,  8,  8,  6,  7,  7,  7,  5,  7,  7,  8,  6,  7,
         7,  6,  7,  8,  9,  8,  8,  8,  5,  7,  8,  7,  8,  8,  8,  7,  7,
         9,  7,  8,  7,  6,  7,  8,  6,  7]),
 60)

In [25]:
n = len(rating)

rv_t = stats.t(n-1)
x_bar = np.mean(rating)
sample_std = np.std(rating, ddof=1)
mu_0 = 7
alpha = 0.01

임계값 접근법 cv

In [27]:
def t_test_cv(n, mu_0, x_bar, sample_std, alpha):
    rv_t = stats.t(n-1)
    t = (x_bar - mu_0) / (sample_std/np.sqrt(n))

    cv = rv_t.isf(alpha)

    if cv <= abs(t):
        print(f"t = {t:.2f}, |t| = {abs(t): .2f} >= cv {cv:.2f}입니다. \n따라서 귀무가설을 기각합니다.")
    else:
        print(f"t = {t:.2f}, |t| = {abs(t): .2f} < cv {cv:.2f}입니다. \n따라서 귀무가설을 기각하지 않습니다.")

t_test_cv(n, mu_0, x_bar, sample_std, alpha)

t = 1.84, |t| =  1.84 < cv 2.39입니다. 
따라서 귀무가설을 기각하지 않습니다.


p-값 접근법

In [28]:
def t_test_p(n, mu_0, x_bar, sample_std, alpha):
    rv_t = stats.t(n-1)
    t = (x_bar - mu_0) / (sample_std/np.sqrt(n))

    if t < 0:
        p_value = rv_t.cdf(t)
    else:
        p_value = rv_t.sf(t) #survival function

    if(p_value < alpha):
        print(f"p_value = {p_value:.2f} < alpha = {alpha: .2f} \n따라서 귀무가설을 기각합니다.")
    else:
        print(f"p_value = {p_value:.2f} >= alpha = {alpha: .2f} \n따라서 귀무가설을 기각하지 않습니다.")

t_test_p(n, mu_0, x_bar, sample_std, alpha)

p_value = 0.04 >= alpha =  0.01 
따라서 귀무가설을 기각하지 않습니다.


모집단 비율에 대한 가설 검정

In [29]:
hairshop_df = pd.read_excel('./data/Hairshop.xlsx')

hairshop_df.head()

Guest
0    Male
1  Female
2    Male
3  Female
4  Female

In [30]:
guest = np.array(hairshop_df['Guest'])
guest.astype('str')

guest, len(guest)

(array(['Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Male',
        'Female', 'Female', 'Female', 'Female', 'Female', 'Female',
        'Female', 'Female', 'Female', 'Female', 'Male', 'Female', 'Female',
        'Female', 'Female', 'Female', 'Female', 'Male', 'Female', 'Female',
        'Female', 'Female', 'Female', 'Male', 'Female', 'Female', 'Female',
        'Male', 'Female', 'Male', 'Female', 'Female', 'Female', 'Female',
        'Female', 'Female', 'Female', 'Female', 'Female', 'Male', 'Male',
        'Female', 'Female', 'Female', 'Female', 'Female', 'Male', 'Female',
        'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female',
        'Male', 'Female', 'Female', 'Male', 'Female', 'Female', 'Female',
        'Female', 'Male', 'Female', 'Male', 'Female', 'Female', 'Female',
        'Female', 'Female', 'Female', 'Female', 'Male', 'Male', 'Female',
        'Female', 'Female', 'Male', 'Male', 'Female', 'Female', 'Female',
        'Female', 'Female', 'Female', 'Fem

In [32]:
n = len(guest)
alpha = 0.01
p_0 = 0.2

male = 0
female = 0

for i in np.arange(n):
    if guest[i] == 'Male':
        male += 1
    else:
        female += 1

male

92

In [42]:
x = 92
p_bar = male / n
se = np.sqrt(p_0 * (1-p_0)/n)
p_bar, se

(0.230, 0.020)

정규근사 조건 충족 여부

In [36]:
if(n>=30 and n * p_bar >= 5 and n*(1-p_bar) >= 5):
    print("정규근사조건 충족함")
else:
    print("정규근사조건 충족하지 못함")

정규근사조건 충족함


임계값 접근법

In [44]:
def z_test_r_cv(x, n, p_0, alpha):
    p_bar = x/n
    rv_z = stats.norm(0, 1)
    se = np.sqrt(p_0 * (1-p_0)/n)
    z = (p_bar - p_0) / se

    cv = rv_z.isf(alpha)

    if abs(z) >= cv:
        print(f"z = {z: .2f}, |z| = {abs(z): .2f} >= cv = {cv:.2f}입니다. \n 따라서 귀무가설을 기각합니다.")
    else:
        print(f"z = {z: .2f}, |z| = {abs(z): .2f} < cv = {cv:.2f}입니다. \n 따라서 귀무가설을 기각하지 않습니다.")

z_test_r_cv(x, n, p_0, alpha)

z =  1.50, |z| =  1.50 < cv = 2.33입니다. 
 따라서 귀무가설을 기각하지 않습니다.


p값 접근법

In [47]:
def z_test_r_p(x, n, p_0, alpha):
    p_bar = x/n
    rv_z = stats.norm(0, 1)
    se = np.sqrt(p_0 * (1-p_0)/n)
    z = (p_bar - p_0) / se

    if(z < 0):
        p_value = rv_z.cdf(z)
    else:
        p_value = rv_z.sf(z)

    if(p_value <= alpha):
        print(f"p_value = {p_value: .4f} <= alpha = {alpha: .2f}입니다. \n 따라서 귀무가설을 기각합니다.")
    else:
        print(f"p_value = {p_value: .4f} > alpha = {alpha: .2f}입니다. \n 따라서 귀무가설을 기각하지 않습니다.")

z_test_r_p(x, n, p_0, alpha)

p_value =  0.0668 > alpha =  0.01입니다. 
 따라서 귀무가설을 기각하지 않습니다.


In [48]:
syrup_df = pd.read_excel('./data/Syrup.xlsx')
syrup_df.head()

Fills
0   999.6
1  1000.5
2  1001.3
3   999.5
4  1000.4

In [49]:
fills = np.array(syrup_df['Fills'])
fills, len(fills)

(array([ 999.6, 1000.5, 1001.3,  999.5, 1000.4, 1000.7,  999.7, 1000.7,
        1000.1, 1000.1,  999.3,  999.6,  999.4,  998.3, 1000.1, 1000.1,
         999.1, 1000. ,  999.2,  999.6,  999.5,  997.8,  998.3,  999.2,
         999.9]),
 25)

In [50]:
n = len(fills)
alpha = 0.05
sample_var = np.var(fills, ddof=1)
var_0 = 1

임계값 접근법

In [53]:
def chi2_test_cv(array, sample_var, var_0, alpha):
    n = len(array)
    rv_chi2 = stats.chi2(n-1)
    chi2 = (n-1) * sample_var / var_0

    cv = rv_chi2.isf(1-alpha)

    if chi2 <= cv:
        print(f"chi2 = {chi2: .2f} <= cv = {cv: .2f}입니다. \n 따라서 귀무가설을 기각합니다.")
    else:
        print(f"chi2 = {chi2: .2f} > cv = {cv: .2f}입니다. \n 따라서 귀무가설을 기각하지 않습니다.")

chi2_test_cv(fills, sample_var, var_0, alpha)

chi2 =  15.20 > cv =  13.85입니다. 
 따라서 귀무가설을 기각하지 않습니다.


p-값 접근법

In [54]:
def chi2_test_p(array, sample_var, var_0, alpha):
    n = len(array)
    rv_chi2 = stats.chi2(n-1)
    chi2 = (n-1) * sample_var / var_0

    p_value = rv_chi2.cdf(chi2)

    if(p_value < alpha):
        print(f"p_value = {p_value: .2f} < alpha = {alpha: .2f}입니다. \n 따라서 귀무가설을 기각합니다.")
    else:
        print(f"p_value = {p_value: .2f} >= alpha = {alpha: .2f}입니다. \n 따라서 귀무가설을 기각하지 않습니다.")

chi2_test_p(fills, sample_var, var_0, alpha)

p_value =  0.09 >= alpha =  0.05입니다. 
 따라서 귀무가설을 기각하지 않습니다.
