In [1]:
import numpy as np
from scipy import linalg as la

In [2]:
#내적 계산
a = np.array([-1, 2, 3])
b = np.array([1, -2, 4])

#원소별 곱 벡터
a * b

array([-1, -4, 12])

In [4]:
#원소별 곱 벡터 합
print(np.sum(a*b))
print(np.inner(a, b))
print(np.dot(a,b))
print(a.T@b)

7
7
7
7


In [6]:
a = np.array([-1,2,3])
b = np.array([1,-2,4])
c = np.array([1,2,3])
alpha = 0.5

In [12]:
#교환 법칙
print(np.dot(a,b) == np.dot(b,a))
print(a.T @ b == b.T @ a)

#결합 법칙
print((alpha * a).T @ b == alpha * (a.T @ b))

#분배 법칙
print((a + b).T @ c == a.T @ c + b.T @ c)

True
True
True
True


In [14]:
# 내적의 활용
a = np.array([1,2,3])
size = len(a)
ones = np.ones(shape=(size,))

# 벡터 원소의 합
np.dot(ones, a)

6.0

In [15]:
np.dot(ones, a) / len(a)

2.0

In [16]:
np.dot(a, a)

14

In [6]:
#L2 norm, euclidean norm
a = np.array([2,3])
np.sqrt(np.sum(np.dot(a, a)))

3.605551275463989

In [7]:
la.norm(a)

3.605551275463989

In [18]:
#과제 3.1
#aT = [1, 2, 3, 4]에 대하여 a / ||a|| 값 구하기

#벡터 표준화
a = np.array([1,2,3,4])
res = a / la.norm(a)
print(res)

[0.18257419 0.36514837 0.54772256 0.73029674]


In [12]:
#과제 3.2 
#a / ||a||에 대하여 || a / || a || ||값 구하기 #시험
# normalization
# 어떤 벡타가 들어와도 결과는 1
la.norm(res)

0.9999999999999999

In [19]:
#벡터 노름의 성질
a = np.array([-1, 2, 3])
b = np.array([1, -2, 4])

#스칼라 곱
beta = 0.5
la.norm(beta * a) == np.abs(beta) * la.norm(a)

True

In [4]:
#삼각형의 한 변의 길이는 다른 두변의 길이 합보다 작다.
la.norm(a+b) <= la.norm(a) + la.norm(b)

True

In [5]:
la.norm(a) >= 0

True

In [21]:
#코사인 theta 구하기
#데이터 구성
a = np.array([1,3])
b = np.array([3,1])

#a.T @ b = ||a|| * ||b|| * cos(theta)
cos_theta_rad = np.dot(a,b) / (la.norm(a)*la.norm(b))

#theta_rad값 구하기
theta_rad = np.arccos(cos_theta_rad)

# 각도 전환: pi radian = 180 degree
theta = theta_rad * (180/np.pi)
[cos_theta_rad, theta]

[0.5999999999999999, 53.13010235415599]

In [8]:
#과제 4.1
#코사인 theta 구하기
#데이터 구성
a = np.array([0,1])
b = np.array([1,0])

cos_theta_rad = np.dot(a,b) / (la.norm(a)*la.norm(b))

#theta_rad값 구하기
theta_rad = np.arccos(cos_theta_rad)

# 각도 전환: pi radian = 180 degree
theta = theta_rad * (180/np.pi)
[cos_theta_rad, theta]

[0.0, 90.0]

In [22]:
#과제 4.2
#코사인 theta 구하기
#데이터 구성
a = np.array([-1,-1])
b = np.array([1,0])

cos_theta_rad = np.dot(a,b) / (la.norm(a)*la.norm(b))

#theta_rad값 구하기
theta_rad = np.arccos(cos_theta_rad)

# 각도 전환: pi radian = 180 degree
theta = theta_rad * (180/np.pi)
[cos_theta_rad, theta]

[-0.7071067811865475, 135.0]

In [67]:
#과제 5.1
#구성된 벡터는 서로 독립인지를 확인 해보자.
a1 = np.array([1,2,3])
a2 = np.array([1,1,2])
a3 = np.array([0.5, 2, 1.5])

A = np.array([[1,2,3],[1,1,2], [0.5, 2, 1.5]])
B = np.array([0,0,0])
C = np.linalg.solve(A, B)
print(C)

[ 0. -0. -0.]


In [75]:
#과제 5.2
#2차원 즉, 평면에서의 기저를 찾아보자.
print("(2,0), (0,2)")
print("(x,0), (0,y) 꼴로 된 벡터는 기저가 될 수 있으며, 평면상 모든 점을 생성할 수 있다.")


(2,0), (0,2)
(x,0), (0,y) 꼴로 된 벡터는 기저가 될 수 있으며, 평면상 모든 점을 생성할 수 있다.


In [74]:
#과제 5.3
# a1, a2, a3가 서로 직교 정교 벡터임을 확인해보자.

#직교정규 벡터 확인
a1 = np.array([0,0,1]).reshape(-1, 1)
a2 = 1/np.sqrt(2) * np.array([1,1,0]).reshape(-1, 1)
a3 = 1/np.sqrt(2) * np.array([1,-1,0]).reshape(-1, 1)

#열의 곱 0
print('각 벡터의 직교 여부')
print("a1.T @ a2 =",np.dot(a1.T,a2))
print("a1.T @ a3 =",np.dot(a1.T,a3))
print("a2.T @ a1 =",np.dot(a2.T,a1))
print("a2.T @ a3 =",np.dot(a2.T,a3))
print("a3.T @ a1 =",np.dot(a3.T,a1))
print("a3.T @ a2 =",np.dot(a3.T,a2))

print()
#노름 1
print('각 벡터의 노름이 1')
print("a1 norm :",la.norm(a1))
print("a2 norm :",la.norm(a2))
print("a3 norm :",la.norm(a3))

A = np.concatenate((a1,a2,a3), axis=1)
print(np.round(A.T @ A, 3))

각 벡터의 직교 여부
a1.T @ a2 = [[0.]]
a1.T @ a3 = [[0.]]
a2.T @ a1 = [[0.]]
a2.T @ a3 = [[0.]]
a3.T @ a1 = [[0.]]
a3.T @ a2 = [[0.]]

각 벡터의 노름이 1
a1 norm : 1.0
a2 norm : 0.9999999999999999
a3 norm : 0.9999999999999999
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]
