In [96]:
import numpy as np
from scipy import linalg as la

### 1) u = a - ||a||e1 값을 구해보자

In [97]:
# u 벡터 구하기
A = np.array(([7,2,0],
              [2,1,3],
              [4,8,3]))

#첫 번째 열벡터 추출
a = A[:,0].reshape(-1, 1)
print("첫 번째 열벡터 추출")
print(a)

첫 번째 열벡터 추출
[[7]
 [2]
 [4]]


In [98]:
# 하우스홀더 행렬 Q1 구성
size = A.shape[0]
e1 = np.identity(n=size)[:,0].reshape(-1,1)

#u 벡터 구성
u = a - la.norm(a)*e1
print("u 벡터 결과 값")
print(u)

u 벡터 결과 값
[[-1.30662386]
 [ 2.        ]
 [ 4.        ]]


### 2) v = u / ||u|| 값을 구해보자

In [99]:
# v 벡터 구하기
v = u / la.norm(u)
print("v 벡터 결과 값")
print(v)

v 벡터 결과 값
[[-0.28044521]
 [ 0.42926693]
 [ 0.85853386]]


### 3) Q1 = I3 - 2vvT 값을 구해보자

In [100]:
Q1 = np.identity(n=size) -2 * v @ v.T
print(np.round(Q1,2))

[[ 0.84  0.24  0.48]
 [ 0.24  0.63 -0.74]
 [ 0.48 -0.74 -0.47]]


### 4) 행렬곱 Q1A의 값을 구해보자

In [101]:
Q1A = np.round(Q1 @ A, 2)
print("Q1A")
print(Q1A)

Q1A
[[ 8.31  5.78  2.17]
 [-0.   -4.78 -0.32]
 [-0.   -3.57 -3.63]]


### 5) A2 = Q1A[1:,1:] 이라고 할 때, A2행렬을 구해보자

In [103]:
A2 = Q1A[1:,1:]
print(A2)

[[-4.78 -0.32]
 [-3.57 -3.63]]


### 6) A2의 첫번째 열 벡터를 a2이라고 할 때, u2 = a2 - ||a2||e1 값을 구해보자

In [95]:
#첫 번째 열벡터 추출
a2 = A2[:,0].reshape(-1, 1)
print("첫 번째 열벡터 추출")
print(a2)

첫 번째 열벡터 추출
[[-4.78]
 [-3.57]]


In [105]:
# 하우스홀더 행렬 Q2 구성
size = 2
e1 = np.identity(n=size)[:,0].reshape(-1,1)

#u 벡터 구성
u2 = a2 - la.norm(a2)*e1
print("u 벡터 결과 값")
print(u2)

u 벡터 결과 값
[[-10.74601207]
 [ -3.57      ]]


### 7) v2 = u2 / ||u2|| 값을 구해보자

In [106]:
# v 벡터 구하기
v2 = u2 / la.norm(u2)
print("v 벡터 결과 값")
print(v2)

v 벡터 결과 값
[[-0.94900085]
 [-0.31527352]]


### 8) q2 = I2 - 2v2v2.T 값을 구해보자

In [107]:
q2 = np.identity(n=2) -2 * v2 @ v2.T
print(np.round(q2,2))

[[-0.8 -0.6]
 [-0.6  0.8]]


### 9) Q2를 생성해보자

In [108]:
Q2 = np.eye(3)
Q2[1:, 1:] = q2
print(Q2)

[[ 1.          0.          0.        ]
 [ 0.         -0.80120522 -0.59838967]
 [ 0.         -0.59838967  0.80120522]]


### 10) R = Q2Q1A의 행렬 곱을 계산해보자

In [132]:
print("Q1A")
print(np.round(Q1@A,2))
print("=======================")
print("Q2Q1A")
R = np.round(Q2@Q1@A, 2)
print(R)
print("=======================")
print("R은 상삼각행렬이다.")

Q1A
[[ 8.31  5.78  2.17]
 [-0.   -4.78 -0.32]
 [-0.   -3.57 -3.63]]
Q2Q1A
[[ 8.31  5.78  2.17]
 [ 0.    5.97  2.43]
 [-0.    0.   -2.72]]
R은 상삼각행렬이다.


### 11) Q = Q1TQ2T를 계산해보자

In [133]:
Q = np.round(Q1.T @ Q2.T,2)
Q

array([[ 0.84, -0.48,  0.24],
       [ 0.24, -0.06, -0.97],
       [ 0.48,  0.87,  0.06]])